version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
  deploy:
    working_directory: ~/app
    docker:
      - image: google/cloud-sdk:217.0.0-alpine
    steps:
      - checkout
      - run: apk add --no-cache nodejs npm yarn
      - run: yarn
      - run: echo $CTF_SPACE_ID | base64 -d > .env
      - run: echo $CTF_ACCESS_TOKEN | base64 -d > .env
      - run: yarn build
      - run: echo $GCLOUD_SERVICE_KEY > ./secret.json
      - run: gcloud auth activate-service-account --key-file=./secret.json
      - run: gcloud app deploy --quiet --project fluid-house-244205

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
